[package]
name = "sitation"
version = "0.1.0"
edition = "2024"

[dependencies]
html5ever = "0.35"
markup5ever_rcdom = "0.35"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1.47", features = ["full"] }
url = "2.5.7"
